Stop including xf86RamDac.h
ramdac drivers have been removed from xserver since version 21.0.99.1
and xorg/xserver@f0385fb4 resulting in the following build failure:

In file included from ../../src/cg3_driver.c:36:
../../src/cg3.h:29:10: fatal error: xf86RamDac.h: No such file or directory
   29 | #include "xf86RamDac.h"
      |          ^~~~~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>